version: '3'

services:
  mysql-container: 
    image: mysql/mysql-server:latest
    container_name: mysql_container
    env_file: ./mysql.env.main
    ports: 
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always 
    volumes: 
      - mysql-volume:/var/lib/mysql

  docker-application:
    image: 950321657511.dkr.ecr.ap-south-1.amazonaws.com/docker_application:1.0.2
    container_name: docker_application
    ports:
      - 8080:8080
    depends_on: 
      - mysql-container
    env_file: ./.env.main
    restart: always
    volumes: 
      - application-volume:/var/lib/logs/
    
volumes:
  mysql-volume:
  application-volume: